### ISSUE TITLE
After step 17: The spawned AP just answers "Not found"

### ISSUE THREAD

**Issue by datenzar** [kadam12g/ESPHome-Shelly-Plus-Plug-S#1]
Hi there,

I followed your step-by-step guide until step 17. Where I picked "Shelly Plus Plug S" (which is the same as my device) and applied the configuration.

After that, the device rebooted but instead of rejoining the network, it spawned an AP with SSID "ShellyPlusPlugS-********". When connecting to the AP, I get an IP in the 192.168.33.x range but if I visit the browser at http://192.168.33.1 then I only see a "Not found" message.

The device itself is slowly but constantly flashing blue.

Does anyone know what I can do here? I already plugged the device out and in again with the same results.

Any help is much appreciated, thanks!

**Comment by kadam12g** [comment]
Hi @datenzar,
After that step, the device should not lose connectivity to the network it was on. I don't know what might be causing that.

But the steps 1-19 are identical to the ones described at https://github.com/tasmota/mgos32-to-tasmota32 . You should try checking the issues for the linked Tasmota Github or search on Tasmota forums, perhaps others have encountered something similar.

If you cannot find anything useful, you can try the steps described here: https://tasmota.github.io/docs/Device-Recovery/ but it's impossible to tell what state the device will revert back to (if it reverts at all.) If the device lost power or got rebooted before or during the auto configuration, then there is a possibility that it may be bricked.

**Comment by datenzar** [comment]
Hi @kadam12g,

thanks for your quick response! I tried the Fast Power Cycle Device Recovery without luck. My guess is that the device is currently running firmware defaults, which might be broken.

However, I found an issue related: https://github.com/tasmota/mgos32-to-tasmota32/issues/75 which I will try to follow.

Thanks

**Comment by datenzar** [comment]
Update: By following the about issue, I was able to reflash the shelly firmware back to the device, but still facing issues (seems like the device configuration is broken).

However, I was able to successfully bring another Shelly Plug Plus S into ESPHome by following your guide by sticking to the version path which - I guess from the date you issued the README - you used.

So flashing Shelly firmware 1.3.3 -> then Tasmota 13.4.1 and continue from there was successful.

I would therefore **not recommend** to the path via 1.4.X -> Tasmota 14.x

**Comment by kadam12g** [comment]
Thanks for the update, I'll add a disclaimer to the guide warning people about this, as currently I don't have any more plugs to try it with and update the guide accurately.

**Comment by Daniel-Boluda** [comment]
Hello!

Just followed the guide and i can confirm it works fine!
Thanks to @kadam12g for it, really really helpfull.

Some questions though,

1.  i didnt "dare" to change the "test" name for different thing, what is the thing behind it?
2.  After making the final updates with "python -m esphome upload test.yaml" , should it be managed from esphome as a "normal" device for further updates?

**Comment by kadam12g** [comment]
Hi @Daniel-Boluda ,

>     1. i didnt "dare" to change the "test" name for different thing, what is the thing behind it?

It's not crucial to use "test" - I just kept it consistent because ESPHome OTA updates use the device name for DNS resolution to find the device IP. If you change the name mid-process, ESPHome won't find the device unless you manually specify the IP with "--device {device_IP}". Using "test" throughout is simpler. Once you're done flashing, you can use ESPHome's "Rename hostname" function to change it properly - it handles the IP resolution automatically.

>     2. After making the final updates with "python -m esphome upload test.yaml" , should it be managed from esphome as a "normal" device for further updates?

Yes, exactly!
